// ═══════════════ DATA ═══════════════
// Global last-verified date — bump this when you re-run program audits.
// Displayed in the topbar and on the landing page so users can see data freshness.
const DATA_LAST_VERIFIED = '2026-05-12';   // YYYY-MM-DD
const DATA_LAST_VERIFIED_LABEL = 'May 2026';

// Each program SHOULD eventually have:
//   mba_level: 'mba_only' | 'mba_and_mim' | 'unknown'   (set during program audit)
//   last_verified: 'YYYY-MM-DD'                          (per-program timestamp)
// For now, programs without these fields default to 'unknown' and the global date.

const DP = [
  {id:1,name:"Amazon Pathways Operations LDP",org:"Amazon",geo:"global",loc:"EU · UAE · India",fn:"operations",sector:"tech",status:"rolling",deadline:"",dlnote:"Rolling — no fixed deadline, apply early",fit:5,visa:true,tags:["MBA","Operations","Rotational"],notes:"3-year career accelerator for MBA graduates. Recruits fall for following year. Strong fit: operations background, 3+ yrs exp. Language skills required for EU postings.",url:"https://www.amazon.jobs/content/en/career-programs/pathways"},
  {id:2,name:"Microsoft Aspire Experience (MBA)",org:"Microsoft",geo:"global",loc:"Dublin · Amsterdam · Dubai",fn:"strategy",sector:"tech",status:"watch",deadline:"2026-10-01",dlnote:"Opens Sep–Oct annually",fit:4,visa:true,tags:["MBA","Product","Strategy"],notes:"Strong Dublin and Dubai presence. Search 'Microsoft Aspire' on LinkedIn for current cohort members. Targets MBA generalists with a product/strategy orientation.",url:"https://careers.microsoft.com"},
  {id:3,name:"Estée Lauder Senior Program Associate",org:"Estée Lauder",geo:"global",loc:"Global (EU · US · Asia)",fn:"general",sector:"consumer",status:"watch",deadline:"2026-09-30",dlnote:"Sep 1–Sep 30 annually",fit:3,visa:false,tags:["MBA","Consumer","Rotational"],notes:"24-month, 4 rotations for MBA grads 5+ yrs exp. Finance, brand, strategy tracks.",url:"https://www.elcompanies.com/en/careers/students/full-time-programs"},
  {id:4,name:"Santander CIB Graduate Program",org:"Santander",geo:"europe",loc:"Spain · UK · Netherlands",fn:"finance",sector:"finance",status:"watch",deadline:"2026-08-01",dlnote:"Opens Aug 2026",fit:4,visa:false,tags:["IB","CIB","Graduate"],notes:"12-month IB immersion. Madrid, London, Paris offices. Strong ESADE network connection.",url:"https://www.santander.com/en/careers"},
  {id:5,name:"DHL Consulting LDP",org:"DHL",geo:"europe",loc:"Bonn, Germany",fn:"consulting",sector:"logistics",status:"rolling",deadline:"",dlnote:"Rolling — check Bonn openings",fit:5,visa:false,tags:["Consulting","Logistics","Strategy"],notes:"Strategy & consulting rotational. Strong supply chain + strategy angle. Bonn-based.",url:"https://careers.dhl.com"},
  {id:6,name:"Unilever Future Leaders Programme",org:"Unilever",geo:"europe",loc:"UK · Netherlands · Global",fn:"general",sector:"consumer",status:"open",deadline:"2026-06-30",dlnote:"Varies by country — check now",fit:3,visa:false,tags:["FMCG","General Mgmt","Rotational"],notes:"Finance, supply chain, strategy tracks. ESADE alumni in Unilever Spain worth contacting.",url:"https://careers.unilever.com/uflp"},
  {id:7,name:"BCG Associate (Full-time MBA)",org:"BCG",geo:"europe",loc:"London · Dubai · Amsterdam",fn:"consulting",sector:"finance",status:"open",deadline:"",dlnote:"Rolling for MBA hires",fit:4,visa:true,tags:["Strategy Consulting","MBA"],notes:"Structured mentorship + clear progression. Strong ESADE + HEC placement history.",url:"https://careers.bcg.com"},
  {id:8,name:"Mastercard MBA Leadership Program",org:"Mastercard",geo:"uae",loc:"UAE · Europe",fn:"strategy",sector:"finance",status:"watch",deadline:"2026-10-15",dlnote:"Opens Sep–Oct annually",fit:4,visa:false,tags:["Fintech","Strategy","MBA"],notes:"Rotational 2-year program. Dubai & London offices hire. Fintech angle aligns well.",url:"https://careers.mastercard.com"},
  {id:9,name:"Mubadala Graduate Programme",org:"Mubadala",geo:"uae",loc:"Abu Dhabi, UAE",fn:"investing",sector:"sovereign",status:"watch",deadline:"",dlnote:"Watch LinkedIn & careers page",fit:5,visa:false,tags:["Sovereign Wealth","PE/VC","UAE"],notes:"Top UAE sovereign fund. PE/VC + healthcare angle is strong fit. Very competitive — limited spots.",url:"https://www.mubadala.com/en/careers/student"},
  {id:10,name:"Chalhoub Group Management Associate",org:"Chalhoub Group",geo:"uae",loc:"Dubai · GCC",fn:"general",sector:"consumer",status:"open",deadline:"",dlnote:"Rolling",fit:3,visa:false,tags:["Luxury Retail","GCC","Rotational"],notes:"Luxury retail conglomerate. Strategy, brand, retail ops rotations across GCC.",url:"https://chalhoubgroup.com/careers"},
  {id:11,name:"Maersk Commercial Graduate Programme",org:"Maersk",geo:"europe",loc:"Copenhagen · Global",fn:"operations",sector:"logistics",status:"open",deadline:"2026-07-15",dlnote:"Rolling intake — check openings",fit:4,visa:true,tags:["Logistics","Supply Chain","Rotational"],notes:"2-year rotational. Strong supply chain + operations angle. Copenhagen HQ with global postings.",url:"https://www.maersk.com/careers/students-and-graduates"},
  {id:12,name:"IFC / World Bank Young Professionals",org:"IFC / World Bank",geo:"global",loc:"Washington / Global",fn:"investing",sector:"sovereign",status:"watch",deadline:"2027-02-01",dlnote:"Typically Jan–Feb each year",fit:5,visa:true,tags:["Impact Investing","DFI","MBA"],notes:"Development finance LDP. PE/VC + impact investing background is standout fit. CFA Level II valued.",url:"https://www.ifc.org/en/careers/ypp"},
  {id:13,name:"Temasek / GIC Graduate Programme",org:"Temasek/GIC",geo:"global",loc:"Singapore (Australia pathway)",fn:"investing",sector:"sovereign",status:"watch",deadline:"2026-10-01",dlnote:"Opens Sep–Oct annually",fit:4,visa:false,tags:["Sovereign Fund","PE/VC","Investments"],notes:"PE/VC background is strong fit. Also a pathway into Australia market.",url:"https://www.temasek.com.sg/en/career"},
  {id:14,name:"Noon.com Strategy & Operations",org:"Noon",geo:"uae",loc:"Dubai, UAE",fn:"operations",sector:"tech",status:"rolling",deadline:"",dlnote:"Rolling — LinkedIn-driven",fit:4,visa:false,tags:["E-commerce","Quick Commerce","Ops"],notes:"Quick commerce and ops background is directly relevant. Strong ops + strategy fit.",url:"https://noon.com/uae-en/careers/"},
  {id:15,name:"Siemens XPS Leadership Program",org:"Siemens",geo:"global",loc:"Munich, Germany · Global",fn:"strategy",sector:"tech",status:"open",deadline:"",dlnote:"Rolling — applications open",fit:5,visa:true,tags:["2-Year","MBA","Tech","Non-rotational"],notes:"2-year direct-entry (non-rotational). Full-time role + leadership training, mentorship, global networking. Ranked #1 Industrial LDP (MBA-Exchange 2025). Good for EU visa holders.",url:"https://www.siemens.com/en-us/company/jobs/growth-careers/siemens-xps-leadership-program/"},
  {id:16,name:"Siemens Finance Excellence Program",org:"Siemens",geo:"europe",loc:"Munich, Germany · Global",fn:"finance",sector:"tech",status:"open",deadline:"",dlnote:"Rolling — check Siemens careers",fit:5,visa:true,tags:["Finance","3 Rotations","MBA","CFO track"],notes:"24-month, 3 rotations across Siemens finance. Munich HQ + international assignment. Targets future CFOs. CFA + finance background is ideal fit. Ranked top Finance LDP (MBA-Exchange 2024/2025).",url:"https://www.siemens.com/en-us/company/jobs/growth-careers/finance-excellence-program/"},
  {id:17,name:"Roche Business Perspectives",org:"Roche",geo:"europe",loc:"Basel, Switzerland · Global",fn:"general",sector:"healthcare",status:"open",deadline:"2026-09-01",dlnote:"Annual intake — Sept 1 start. Assessment centre mid-May 2026.",fit:4,visa:true,tags:["Healthcare","Rotational","MBA","4 Rotations"],notes:"2-year rotational, up to 4 assignments of 6–8 months. Pharma, Diagnostics, Group functions. Requires MBA + 3–5 yrs exp. Application includes 4-slide presentation. Up to 12 spots.",url:"https://careers.roche.com/global/en/business-perspectives-at-roche"},
  {id:18,name:"Samsung Global Strategy Group (GSG)",org:"Samsung",geo:"global",loc:"Seoul, South Korea",fn:"strategy",sector:"tech",status:"rolling",deadline:"",dlnote:"Recruits mid-year for next cohort",fit:3,visa:false,tags:["Internal Consulting","MBA","Strategy"],notes:"Elite internal strategy consulting arm of Samsung. Seoul-based. Strong strategy/consulting background required.",url:"https://www.sgsg.samsung.com"},
  {id:19,name:"J&J IRDP (Intl Recruitment & Dev)",org:"Johnson & Johnson",geo:"global",loc:"EMEA · APAC · Americas",fn:"general",sector:"healthcare",status:"open",deadline:"",dlnote:"Rolling — multiple intakes globally",fit:5,visa:false,tags:["Healthcare","MBA","Multi-function","IRDP"],notes:"J&J's flagship MBA LDP. Available across EMEA (Spain, UK, France, Netherlands, Germany). Non-rotational but accelerated. Ranked #1 globally by MBA-Exchange. Strong ESADE → J&J Spain pipeline.",url:"https://www.careers.jnj.com/en/student-opportunities/leadership-development-programs/"},
  {id:20,name:"Bayer Leadership Development Program",org:"Bayer",geo:"europe",loc:"Leverkusen, Germany · Global",fn:"general",sector:"healthcare",status:"watch",deadline:"",dlnote:"Watch careers.bayer.com",fit:4,visa:true,tags:["Healthcare","Pharma","Rotational","MBA"],notes:"Rotational program across Bayer's Pharma, Crop Science, Consumer Health. Germany HQ + international assignments.",url:"https://careers.bayer.com/en"},
  {id:21,name:"Hilti Outperformer (Global Mgmt Dev)",org:"Hilti",geo:"global",loc:"Schaan, Liechtenstein · Global",fn:"general",sector:"industrial",status:"open",deadline:"",dlnote:"Rolling — continuous recruitment",fit:4,visa:true,tags:["General Mgmt","Rotational","MBA","IMD"],notes:"Prestigious rotational program with IMD Business School qualification included. Commercial + operational track. 120+ countries. Strong fit for general management aspirants.",url:"https://careers.hilti.com/en/students-and-recent-graduates"},
  {id:22,name:"PwC Strategy& MBA Associate",org:"PwC Strategy&",geo:"europe",loc:"London · Amsterdam · Dubai",fn:"consulting",sector:"finance",status:"open",deadline:"",dlnote:"Rolling — check pwc.com/strategand",fit:4,visa:true,tags:["Consulting","Strategy","MBA","MBB-Adjacent"],notes:"Strategy& is PwC's strategy consulting arm — MBB-adjacent calibre. Strong ESADE/HEC placement. London, Amsterdam, Dubai offices hire MBA Associates. Finance + ops background is a strong angle.",url:"https://www.strategyand.pwc.com/gx/en/careers.html"},
  {id:23,name:"Emerson Europe Rotational MBA",org:"Emerson",geo:"europe",loc:"Europe (multiple countries)",fn:"operations",sector:"industrial",status:"open",deadline:"",dlnote:"Rolling — check Emerson careers",fit:4,visa:true,tags:["Operations","Industrial","Rotational","MBA"],notes:"Europe-focused rotational MBA program. Emerson consistently top-5 LDP employer globally. Strong ops, supply chain, tech angle.",url:"https://www.emerson.com/en-us/careers"},
  {id:24,name:"WEF Global Leadership Fellows (GLFP)",org:"World Economic Forum",geo:"global",loc:"Geneva, Switzerland",fn:"strategy",sector:"sovereign",status:"watch",deadline:"2026-10-01",dlnote:"Annual — typically Sep/Oct deadline",fit:5,visa:false,tags:["Impact","Policy","MBA","Global"],notes:"Highly selective 3-year fellowship at WEF Geneva. Strong fit: impact investing, PE/VC, emerging markets. Network 12+ months in advance. Requires strong policy/systems thinking angle.",url:"https://www.weforum.org/about/fellows/"},
  {id:25,name:"Sanofi Management Associate Program",org:"Sanofi",geo:"global",loc:"Paris, France · Global",fn:"general",sector:"healthcare",status:"open",deadline:"",dlnote:"Rolling — check jobs.sanofi.com",fit:5,visa:true,tags:["Healthcare","MBA","Commercial","Rotational"],notes:"#1 Healthcare LDP and #1 Management LDP globally (MBA-Exchange 2025). Rotational across commercial, market access, strategy. Paris HQ + global.",url:"https://jobs.sanofi.com/en/early-talent"},
  {id:26,name:"Emerson MBA Leadership Program",org:"Emerson",geo:"global",loc:"St. Louis, USA · Europe",fn:"operations",sector:"industrial",status:"open",deadline:"",dlnote:"Rolling — check emerson.com/careers",fit:5,visa:true,tags:["Operations","Industrial","MBA","Full-time"],notes:"#1 Industrial Products LDP (MBA-Exchange 2024). Consistently top-3 most-viewed employer globally. Full-time MBA leadership role.",url:"https://www.emerson.com/en-us/careers"},
  {id:27,name:"Schneider Electric Sustainability LDP",org:"Schneider Electric",geo:"global",loc:"Paris, France · Global",fn:"strategy",sector:"energy",status:"open",deadline:"",dlnote:"Rolling — check se.com/careers",fit:4,visa:true,tags:["Sustainability","Energy","MBA","Rotational"],notes:"#1 Energy LDP and #1 Rotational program globally (MBA-Exchange 2025). Sustainability + digital transformation focus. Paris HQ. Strong ESG angle.",url:"https://www.se.com/ww/en/about-us/careers/"},
  {id:28,name:"Novo Nordisk Intl Ops Graduate",org:"Novo Nordisk",geo:"global",loc:"Copenhagen, Denmark",fn:"operations",sector:"healthcare",status:"open",deadline:"",dlnote:"Rolling — check novonordisk.com",fit:4,visa:true,tags:["Operations","Healthcare","Pharma","Rotational"],notes:"Top 4 Operations LDP (MBA-Exchange 2025). International graduate program across supply chain and operations. Copenhagen HQ.",url:"https://www.novonordisk.com/careers.html"},
  {id:29,name:"Samsara Global Operations Rotation",org:"Samsara",geo:"global",loc:"San Francisco, USA",fn:"operations",sector:"tech",status:"open",deadline:"",dlnote:"Rolling — check samsara.com/careers",fit:3,visa:false,tags:["Operations","Tech","IoT","MBA"],notes:"#1 Operations LDP (MBA-Exchange 2025). Industrial IoT / fleet tech. US-based fast-riser in LDP rankings.",url:"https://www.samsara.com/company/careers"},
  {id:30,name:"Philips Full-Time Operations LDP",org:"Philips",geo:"europe",loc:"Amsterdam, Netherlands",fn:"operations",sector:"healthcare",status:"watch",deadline:"",dlnote:"Watch careers.philips.com",fit:4,visa:true,tags:["Operations","Healthcare","MBA","Netherlands"],notes:"Top 7 Operations LDP (MBA-Exchange 2025). Amsterdam-based. Healthcare + supply chain + ops angle. EU work authorisation relevant.",url:"https://www.careers.philips.com"},
  {id:31,name:"Arkema MBA Leadership Development",org:"Arkema",geo:"europe",loc:"Paris, France · Global",fn:"general",sector:"industrial",status:"open",deadline:"",dlnote:"Rolling — check arkema.com/careers",fit:4,visa:true,tags:["Industrial","MBA","Rotational","France"],notes:"Top 4 Rotational and top 7 Industrial LDP (MBA-Exchange 2025). French specialty chemicals. Paris HQ. Strong ESADE + HEC France connection.",url:"https://www.arkema.com/global/en/careers/"},
  {id:32,name:"Vanguard MBA Development Program",org:"Vanguard",geo:"global",loc:"Malvern, PA, USA",fn:"finance",sector:"finance",status:"open",deadline:"",dlnote:"Rolling — check vanguardjobs.com",fit:3,visa:false,tags:["Finance","Asset Management","MBA","Rotational"],notes:"#1 Finance LDP globally (MBA-Exchange 2025). Asset management focus. US-headquartered.",url:"https://www.vanguardjobs.com"},
  {id:33,name:"J&J Finance MBA LDP (FLDP)",org:"Johnson & Johnson",geo:"global",loc:"New Jersey, USA · Global",fn:"finance",sector:"healthcare",status:"open",deadline:"",dlnote:"Rolling — separate from IRDP track",fit:4,visa:false,tags:["Finance","Healthcare","MBA","4-Year"],notes:"4-year rotational finance program. Covers treasury, business development, supply chain finance, R&D finance. CFA Level II is a strong differentiator. Separate from J&J IRDP.",url:"https://www.careers.jnj.com/en/student-opportunities/leadership-development-programs/"},
  {id:34,name:"Kraft Heinz MBA Leadership Program",org:"Kraft Heinz",geo:"global",loc:"Chicago, USA · Global",fn:"general",sector:"consumer",status:"watch",deadline:"2026-09-01",dlnote:"Annual — opens mid-year",fit:3,visa:false,tags:["Consumer","FMCG","MBA","Strategy"],notes:"Top 4 Consumer LDP and top Finance LDP (MBA-Exchange 2025). Strategy + finance focus.",url:"https://careers.kraftheinzcompany.com"},
  {id:35,name:"Cartier Aspire (Richemont) Rotational",org:"Cartier (Richemont)",geo:"global",loc:"Geneva · Paris · Global",fn:"general",sector:"consumer",status:"open",deadline:"",dlnote:"Rolling — check careers.richemont.com",fit:4,visa:false,tags:["Luxury","Consumer","MBA","Rotational"],notes:"Top 2 Consumer LDP (MBA-Exchange 2025). Luxury goods rotational. Geneva and Paris-based.",url:"https://careers.richemont.com"},
  {id:36,name:"Abbott MBA Commercial LDP",org:"Abbott",geo:"global",loc:"Chicago, USA · Global",fn:"general",sector:"healthcare",status:"open",deadline:"",dlnote:"Rolling — check abbott.com/careers",fit:3,visa:false,tags:["Healthcare","MBA","Commercial","Medical Devices"],notes:"#1 Sales & Marketing LDP (MBA-Exchange 2025). Commercial leadership across medical devices and diagnostics.",url:"https://www.abbott.com/careers.html"},
  {id:37,name:"Admiral Group MBA Future Leaders",org:"Admiral Group",geo:"europe",loc:"Cardiff, UK",fn:"strategy",sector:"finance",status:"open",deadline:"",dlnote:"Rolling — check jobs.admiral.com",fit:3,visa:false,tags:["Insurance","Finance","MBA","UK"],notes:"Top 10 Europe LDP and top Financial Services LDP (MBA-Exchange 2025). Group Strategy Manager track. Smaller firm = faster progression.",url:"https://jobs.admiral.com"},
  {id:38,name:"BASF MBA Leadership Development",org:"BASF",geo:"europe",loc:"Ludwigshafen, Germany",fn:"general",sector:"industrial",status:"open",deadline:"",dlnote:"Rolling — check basf.com/careers",fit:4,visa:true,tags:["Industrial","Chemicals","MBA","Rotational"],notes:"#1 Industrial Products LDP (MBA-Exchange 2025, multiple years). 3 rotations of 8 months including one international. Strong ESADE → Germany pipeline.",url:"https://www.basf.com/global/en/careers.html"},
  {id:39,name:"ThermoFisher Scientific MBA Program",org:"ThermoFisher",geo:"global",loc:"Waltham, USA · Global",fn:"general",sector:"healthcare",status:"open",deadline:"",dlnote:"Rolling — check thermofisher.com/careers",fit:3,visa:true,tags:["Healthcare","Life Sciences","MBA","Commercial"],notes:"Top 5 Healthcare LDP (MBA-Exchange 2024/2025). Life sciences tools + diagnostics. Commercial and operations tracks.",url:"https://jobs.thermofisher.com"},
  {id:40,name:"CFO Insights Leadership Program (MBA Graduate)",org:"CFO Insights",geo:"europe",loc:"UK · Europe",fn:"finance",sector:"finance",status:"open",deadline:"",dlnote:"Rolling — check cfoi.co.uk",fit:4,visa:false,tags:["Finance","MBA","Leadership","CFO Track"],notes:"#1 Financial Services LDP globally (MBA-Exchange 2025). Fast-track CFO development program. Finance modeling, FP&A, strategic finance. Strong CFA Level II alignment.",url:"https://www.cfoi.co.uk"},
  {id:41,name:"AB InBev Global MBA Program",org:"AB InBev",geo:"global",loc:"Global (Belgium · Brazil · USA)",fn:"general",sector:"consumer",status:"watch",deadline:"2026-09-01",dlnote:"Annual — opens mid-year",fit:3,visa:true,tags:["Consumer","FMCG","MBA","Rotational","#1 Global"],notes:"#1 ranked LDP globally (MBA-Exchange 2025). Three rotations tied to global strategic pillars. Highly competitive. HEC Paris has placement history.",url:"https://www.ab-inbev.com/career/global-management-trainee-programs"},
  {id:42,name:"Arkema Top Start International Business Leader",org:"Arkema",geo:"europe",loc:"Paris, France · Global",fn:"general",sector:"industrial",status:"open",deadline:"",dlnote:"Rolling — check arkema.com/careers",fit:4,visa:true,tags:["Industrial","MBA","Rotational","France","Top Start"],notes:"Top Start: 18-month international rotational for MBAs. Paris HQ. Specialty chemicals. ESADE + HEC France alumni network strong. Top 4 Rotational LDP (MBA-Exchange 2025).",url:"https://www.arkema.com/global/en/careers/"},
  {id:43,name:"Eli Lilly Connected MBA (cMBA) Program",org:"Eli Lilly",geo:"global",loc:"Indianapolis, USA · Europe · Asia",fn:"general",sector:"healthcare",status:"open",deadline:"",dlnote:"Rolling — multiple functions and geographies",fit:4,visa:true,tags:["Healthcare","Pharma","Rotational","MBA","Multi-function"],notes:"Eli Lilly's cMBA spans finance, marketing, operations, HR, and IT tracks across global geographies. Indianapolis HQ with international rotations. Strong pharma + healthcare background fit.",url:"https://www.lilly.com/careers/students-and-graduates"},
  {id:44,name:"Galderma Finance Catalyst Program",org:"Galderma",geo:"europe",loc:"Zug, Switzerland · Global",fn:"finance",sector:"healthcare",status:"open",deadline:"",dlnote:"Rolling — check galderma.com/careers",fit:4,visa:false,tags:["Finance","Healthcare","Dermatology","MBA","Switzerland"],notes:"Finance-focused rotational at Galderma (world's largest pure-play dermatology company). Zug HQ. CFA + finance background is a strong differentiator. Fast-growing post-Nestlé spinoff.",url:"https://www.galderma.com/careers"},
  {id:45,name:"Insud Pharma Leadership Development Program",org:"Insud Pharma",geo:"europe",loc:"Madrid, Spain · LATAM · EMEA",fn:"general",sector:"healthcare",status:"watch",deadline:"",dlnote:"Watch LinkedIn and insudpharma.com/careers",fit:3,visa:false,tags:["Healthcare","Pharma","MBA","Spain","LATAM"],notes:"Insud Pharma (Chemo Group) covers commercial, operations, and R&D tracks. Madrid-based with LATAM and EMEA exposure. Strong ESADE → Spain pharma pipeline.",url:"https://www.insudpharma.com/en/careers"},
  {id:46,name:"Ipsen SPARK MBA Program",org:"Ipsen",geo:"europe",loc:"Paris, France · Global",fn:"general",sector:"healthcare",status:"open",deadline:"",dlnote:"Rolling — check ipsen.com/careers",fit:4,visa:true,tags:["Healthcare","Pharma","MBA","France","SPARK","Rotational"],notes:"2-year rotational for MBA graduates across commercial, medical affairs, and strategy. Paris HQ + global assignments. Oncology, rare diseases, neuroscience focus. Strong HEC Paris pipeline.",url:"https://www.ipsen.com/careers/"},
  {id:47,name:"Novartis MBA Leadership Associate",org:"Novartis",geo:"global",loc:"Basel, Switzerland · Global",fn:"general",sector:"healthcare",status:"open",deadline:"",dlnote:"Rolling — check novartis.com/careers",fit:5,visa:true,tags:["Healthcare","Pharma","MBA","Switzerland","Leadership"],notes:"Novartis recruits MBAs into leadership associate roles across strategy, commercial, and business development. Basel HQ + global postings. Strong fit: PE/VC healthcare background, CFA Level II.",url:"https://www.novartis.com/careers"},
  {id:48,name:"AstraZeneca MBA Graduate Program",org:"AstraZeneca",geo:"europe",loc:"Cambridge, UK · Global",fn:"general",sector:"healthcare",status:"open",deadline:"",dlnote:"Rolling — check astrazeneca.com/careers",fit:4,visa:true,tags:["Healthcare","Pharma","MBA","UK","Commercial"],notes:"Places MBAs across commercial, finance, and operations globally. Cambridge UK HQ. Strong oncology + rare disease portfolio. EU and UK postings available.",url:"https://careers.astrazeneca.com"}
];

const DA = [
  {id:1,name:"[Find via LinkedIn]",school:"esade",firm:"Amazon",role:"Pathways Operations Manager",loc:"EU / UK",status:"identified",prog:"Amazon Pathways",li:"https://www.linkedin.com/school/esade/people/?keywords=amazon",notes:"Search ESADE alumni → 'amazon'. Target people who joined in last 2 years."},
  {id:2,name:"[Find via LinkedIn]",school:"hec",firm:"BCG",role:"Associate / Consultant",loc:"Dubai / London",status:"identified",prog:"BCG",li:"https://www.linkedin.com/school/hec-paris/people/?keywords=bcg",notes:"HEC Paris alumni filtered by 'bcg'. Filter further by Dubai or London."},
  {id:3,name:"[Find via LinkedIn]",school:"esade",firm:"IFC / World Bank",role:"Young Professional",loc:"Washington / Global",status:"identified",prog:"IFC YPP",li:"https://www.linkedin.com/school/esade/people/?keywords=IFC",notes:"Search ESADE alumni at IFC. Impact investing background is a strong opener."},
  {id:4,name:"[Find via LinkedIn]",school:"hec",firm:"Mubadala",role:"Investment Associate",loc:"Abu Dhabi",status:"identified",prog:"Mubadala Graduate",li:"https://www.linkedin.com/school/hec-paris/people/?keywords=mubadala",notes:"HEC Paris has strong MENA alumni. Reach out 6–8 weeks before apps open."},
  {id:5,name:"[Find via LinkedIn]",school:"esade",firm:"Santander",role:"Graduate Analyst",loc:"Madrid / London",status:"identified",prog:"Santander CIB",li:"https://www.linkedin.com/school/esade/people/?keywords=santander",notes:"ESADE has direct pipeline to Santander Spain. Check ESADE careers office for warm intros."},
  {id:6,name:"[Find via LinkedIn]",school:"hec",firm:"Mastercard",role:"MBA Leadership Program",loc:"Dubai / Paris",status:"identified",prog:"Mastercard MBA LDP",li:"https://www.linkedin.com/school/hec-paris/people/?keywords=mastercard",notes:"Search HEC alumni at Mastercard in UAE / Europe. Fintech + strategy is a strong common thread."},
  {id:7,name:"[Find via LinkedIn]",school:"esade",firm:"Maersk",role:"Commercial Graduate",loc:"Copenhagen / BCN",status:"identified",prog:"Maersk Commercial",li:"https://www.linkedin.com/school/esade/people/?keywords=maersk",notes:"Maersk has recruited from ESADE. Target alumni in supply chain or commercial strategy."},
  {id:8,name:"[Find via LinkedIn]",school:"hec",firm:"Microsoft",role:"Aspire Experience MBA",loc:"Paris / Dublin",status:"identified",prog:"Microsoft Aspire",li:"https://www.linkedin.com/school/hec-paris/people/?keywords=microsoft",notes:"HEC has strong Microsoft Europe placement. Look for people who started in last 2 years."},
  {id:9,name:"[Find via LinkedIn]",school:"esade",firm:"Siemens",role:"XPS / FEP Program",loc:"Munich / Europe",status:"identified",prog:"Siemens XPS / FEP",li:"https://www.linkedin.com/school/esade/people/?keywords=siemens",notes:"Siemens actively recruits from European schools. Great for EU visa holders. Check both XPS and FEP programs."},
  {id:10,name:"[Find via LinkedIn]",school:"hec",firm:"Roche",role:"Business Perspectives",loc:"Basel / Global",status:"identified",prog:"Roche Business Perspectives",li:"https://www.linkedin.com/school/hec-paris/people/?keywords=roche",notes:"HEC Paris has strong Roche alumni network. Application requires a 4-slide case presentation. Programme starts Sept 1 annually."},
  {id:11,name:"[Find via LinkedIn]",school:"esade",firm:"Johnson & Johnson",role:"IRDP Participant",loc:"Spain / EMEA",status:"identified",prog:"J&J IRDP",li:"https://www.linkedin.com/school/esade/people/?keywords=johnson+johnson",notes:"J&J IRDP has strong ESADE Spain presence. Warm intro via ESADE careers office is likely possible."},
  {id:12,name:"[Find via LinkedIn]",school:"hec",firm:"AB InBev",role:"Global MBA Program",loc:"Global",status:"identified",prog:"AB InBev Global MBA",li:"https://www.linkedin.com/school/hec-paris/people/?keywords=ab+inbev",notes:"AB InBev is #1 globally ranked LDP. HEC Paris has placement history."},
  {id:13,name:"[Find via LinkedIn]",school:"esade",firm:"Emerson",role:"Europe Rotational MBA",loc:"Europe",status:"identified",prog:"Emerson Europe Rotational",li:"https://www.linkedin.com/school/esade/people/?keywords=emerson",notes:"Emerson consistently top-5 LDP employer. Search 'emerson' in ESADE alumni for European cohort members."},
  {id:14,name:"[Find via LinkedIn]",school:"hec",firm:"World Economic Forum",role:"Global Leadership Fellow",loc:"Geneva, Switzerland",status:"identified",prog:"WEF GLFP",li:"https://www.linkedin.com/school/hec-paris/people/?keywords=world+economic+forum",notes:"WEF GLFP is highly selective. HEC Paris has alumni in Geneva. Network 12+ months in advance."},
  {id:15,name:"[Find via LinkedIn]",school:"esade",firm:"Sanofi",role:"Management Associate",loc:"Paris / Global",status:"identified",prog:"Sanofi MAP",li:"https://www.linkedin.com/school/esade/people/?keywords=sanofi",notes:"Sanofi is #1 globally (MBA-Exchange 2025). Strong ESADE Spain pipeline. Healthcare background is a standout angle."}
];
